# Generated by Django 5.1 on 2024-12-12 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('email', models.EmailField(max_length=254, verbose_name='E-Mail')),
                ('message', models.TextField(max_length=200, verbose_name='Mensagemm')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('response', models.TextField(max_length=200, null=True, verbose_name='Resposta')),
                ('response_sent_at', models.DateTimeField(null=True, verbose_name='Respondido em')),
                ('flag', models.BooleanField(default=False, verbose_name='Já foi respondido')),
            ],
            options={
                'verbose_name': 'contato',
                'verbose_name_plural': 'contatos',
                'ordering': ('-created_at',),
            },
        ),
    ]
