# Generated by Django 5.1 on 2024-12-14 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(max_length=200, verbose_name='Mensagem'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='response_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Respondido em'),
        ),
    ]
