# Generated by Django 5.1 on 2024-12-14 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_alter_contact_message_alter_contact_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='response',
        ),
    ]
